# python train_model_graph_valenceN_test.py -w '../weights/Emotion_Fold_0_Conv_Channel_Valence_43_99.7766.pkl' -f 'EEG_0'
# python train_model_graph_valenceN_test.py -w '../weights/Emotion_Fold_1_Conv_Channel_Valence_4_67.5735.pkl' -f 'EEG_1'
# python train_model_graph_valenceN_test.py -w '../weights/Emotion_Fold_2_Conv_Channel_Valence_31_38.2446.pkl' -f 'EEG_2'
# python train_model_graph_valenceN_test.py -w '../weights/Emotion_Fold_3_Conv_Channel_Valence_24_68.0545.pkl' -f 'EEG_3'
# python train_model_graph_valenceN_test.py -w '../weights/Emotion_Fold_4_Conv_Channel_ValenceN_24_81.3075.pkl' -f 'EEG_4'
# python train_model_graph_valenceN_test.py -w '../weights/Emotion_Fold_5_Conv_Channel_ValenceN_4_60.8746.pkl' -f 'EEG_5'
# python train_model_graph_valenceN_test.py -w '../weights/Emotion_Fold_6_Conv_Channel_ValenceN_3_63.5941.pkl' -f 'EEG_6'
# python train_model_graph_valenceN_test.py -w '../weights/Emotion_Fold_7_Conv_Channel_ValenceN_3_46.5559.pkl' -f 'EEG_7'
# python train_model_graph_valenceN_test.py -w '../weights/Emotion_Fold_8_Conv_Channel_ValenceN_2_72.1194.pkl' -f 'EEG_8'
# python train_model_graph_valenceN_test.py -w '../weights/Emotion_Fold_9_Conv_Channel_ValenceN_9_68.1935.pkl' -f 'EEG_9'

# python train_model_graph_arousalN_test.py -w '../weights/Emotion_Fold_0_Conv_Channel_Arousal_1_71.7157.pkl' -f 'EEG_0'
# python train_model_graph_arousalN_test.py -w '../weights/Emotion_Fold_1_Conv_Channel_Arousal_33_54.9277.pkl' -f 'EEG_1'
# python train_model_graph_arousalN_test.py -w '../weights/Emotion_Fold_2_Conv_Channel_Arousal_1_52.3886.pkl' -f 'EEG_2'
# python train_model_graph_arousalN_test.py -w '../weights/Emotion_Fold_3_Conv_Channel_Arousal_3_58.8342.pkl' -f 'EEG_3'
# python train_model_graph_arousalN_test.py -w '../weights/Emotion_Fold_4_Conv_Channel_ArousalN_29_58.9664.pkl' -f 'EEG_4'
# python train_model_graph_arousalN_test.py -w '../weights/Emotion_Fold_5_Conv_Channel_ArousalN_24_64.5761.pkl' -f 'EEG_5'
# python train_model_graph_arousalN_test.py -w '../weights/Emotion_Fold_6_Conv_Channel_ArousalN_76_49.5.pkl' -f 'EEG_6'
# python train_model_graph_arousalN_test.py -w '../weights/Emotion_Fold_7_Conv_Channel_ArousalN_1_67.5168.pkl' -f 'EEG_7'
# python train_model_graph_arousalN_test.py -w '../weights/Emotion_Fold_8_Conv_Channel_ArousalN_11_61.5722.pkl' -f 'EEG_8'
# python train_model_graph_arousalN_test.py -w '../weights/Emotion_Fold_9_Conv_Channel_ArousalN_24_54.3106.pkl' -f 'EEG_9'

# python train_model_graph_arousalR_test.py -w '../weights/Emotion_Fold_0_Conv_Channel_ArousalR_20_59.8294.pkl' -f 'EEG_0'
# python train_model_graph_arousalR_test.py -w '../weights/Emotion_Fold_1_Conv_Channel_ArousalR_4_64.1233.pkl' -f 'EEG_1'
# python train_model_graph_arousalR_test.py -w '../weights/Emotion_Fold_2_Conv_Channel_ArousalR_17_59.0469.pkl' -f 'EEG_2'
# python train_model_graph_arousalR_test.py -w '../weights/Emotion_Fold_3_Conv_Channel_ArousalR_1_64.9234.pkl' -f 'EEG_3'
# python train_model_graph_arousalR_test.py -w '../weights/Emotion_Fold_4_Conv_Channel_ArousalR_11_55.0483.pkl' -f 'EEG_4'
# python train_model_graph_arousalR_test.py -w '../weights/Emotion_Fold_5_Conv_Channel_ArousalR_4_60.9513.pkl' -f 'EEG_5'
# python train_model_graph_arousalR_test.py -w '../weights/Emotion_Fold_6_Conv_Channel_ArousalR_1_58.5747.pkl' -f 'EEG_6'
# python train_model_graph_arousalR_test.py -w '../weights/Emotion_Fold_7_Conv_Channel_ArousalR_14_55.181.pkl' -f 'EEG_7'
# python train_model_graph_arousalR_test.py -w '../weights/Emotion_Fold_8_Conv_Channel_ArousalR_1_53.8314.pkl' -f 'EEG_8'
# python train_model_graph_arousalR_test.py -w '../weights/Emotion_Fold_9_Conv_Channel_ArousalR_28_58.7388.pkl' -f 'EEG_9'

# python train_model_graph_valenceR_test.py -w '../weights/Emotion_Fold_0_Conv_Channel_ValenceR_1_60.9824.pkl' -f 'EEG_0'
# python train_model_graph_valenceR_test.py -w '../weights/Emotion_Fold_1_Conv_Channel_ValenceR_1_60.3233.pkl' -f 'EEG_1'
# python train_model_graph_valenceR_test.py -w '../weights/Emotion_Fold_2_Conv_Channel_ValenceR_1_58.8123.pkl' -f 'EEG_2'
# python train_model_graph_valenceR_test.py -w '../weights/Emotion_Fold_3_Conv_Channel_ValenceR_15_58.866.pkl' -f 'EEG_3'
# python train_model_graph_valenceR_test.py -w '../weights/Emotion_Fold_4_Conv_Channel_ValenceR_2_62.9335.pkl' -f 'EEG_4'
# python train_model_graph_valenceR_test.py -w '../weights/Emotion_Fold_5_Conv_Channel_ValenceR_32_62.4097.pkl' -f 'EEG_5'
# python train_model_graph_valenceR_test.py -w '../weights/Emotion_Fold_6_Conv_Channel_ValenceR_4_63.5038.pkl' -f 'EEG_6'
# python train_model_graph_valenceR_test.py -w '../weights/Emotion_Fold_7_Conv_Channel_ValenceR_1_59.2238.pkl' -f 'EEG_7'
# python train_model_graph_valenceR_test.py -w '../weights/Emotion_Fold_8_Conv_Channel_ValenceR_4_70.0378.pkl' -f 'EEG_8'
# python train_model_graph_valenceR_test.py -w '../weights/Emotion_Fold_9_Conv_Channel_ValenceR_1_60.7163.pkl' -f 'EEG_9'


python train_model_graph_dominanceN_test.py -w '../weights/Emotion_Fold_0_Conv_Channel_DominanceN_2_57.6244.pkl' -f 'EEG_0'
python train_model_graph_dominanceN_test.py -w '../weights/Emotion_Fold_1_Conv_Channel_DominanceN_11_50.8916.pkl' -f 'EEG_1'
python train_model_graph_dominanceN_test.py -w '../weights/Emotion_Fold_2_Conv_Channel_DominanceN_15_51.6332.pkl' -f 'EEG_2'
python train_model_graph_dominanceN_test.py -w '../weights/Emotion_Fold_3_Conv_Channel_DominanceN_6_64.2723.pkl' -f 'EEG_3'
python train_model_graph_dominanceN_test.py -w '../weights/Emotion_Fold_4_Conv_Channel_DominanceN_3_61.5065.pkl' -f 'EEG_4'
python train_model_graph_dominanceN_test.py -w '../weights/Emotion_Fold_5_Conv_Channel_DominanceN_2_72.2746.pkl' -f 'EEG_5'
python train_model_graph_dominanceN_test.py -w './weights/Emotion_Fold_6_Conv_Channel_DominanceN_44_54.0235.pkl' -f 'EEG_6'

